### ISSUE TITLE
Strange question, have you ever met ?

### ISSUE THREAD

**Issue by niuniu111** [visipedia/tfrecords#3]
Running this error on windows will not happen on Ubuntu:OverflowError: Python int too large to convert to C long.
def _int64_feature(value):
    return tf.train.Feature(int64_list=tf.train.Int64List(value=[value]))
I want to modify the Int64 bit uint32, but tensorflow only supports Int64, float, string. What should I do?

**Comment by gvanhorn38** [comment]
Right, by default the tfrecords can only store bytes, floats and int64 data types (see the protocol definition [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/example/feature.proto)). If you really need to store uint32 data types then you could:
1.  do your own conversion to and from int64
2. store the uint32 as a byte string that you can parse later on
3. change the definition and recompile the tfrecord protocol buffers so that they use uint32. Or just create your own protocol buffer that is more appropriate for your data.
